apiVersion: v1
data:
  bucket-key: {{ .Values.secrets.key | default "" }}
  bucket-secret: {{ .Values.secrets.secret | default "" }}
kind: Secret
metadata:
  name: {{ include "swarm.fullname" . }}-podlister
  labels:
    {{- include "swarm.labels" . | nindent 4 }}
