apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "swarm.fullname" .}}-cj
  labels:
    {{- include "swarm.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Chart.Name }}"
            image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
            env:
            - name: BUCKET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "swarm.fullname" . }}-podlister
                  key: bucket-key
            - name: BUCKET_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "swarm.fullname" . }}-podlister
                  key: bucket-secret
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "swarm.fullname" . }}-podlister
                  key: service-name

          restartPolicy: OnFailure
          serviceAccount: {{ include "swarm.serviceAccountName" . }} 
